2021-12-09 09:24:26,211 INFO    MainThread:12500 [wandb_setup.py:_flush():71] setting env: {}
2021-12-09 09:24:26,211 INFO    MainThread:12500 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-09 09:24:26,211 INFO    MainThread:12500 [wandb_init.py:_log_setup():371] Logging user logs to D:\rushan\II\lab3\II_Group1_Lab3\wandb\run-20211209_092426-8gooktbx\logs\debug.log
2021-12-09 09:24:26,211 INFO    MainThread:12500 [wandb_init.py:_log_setup():372] Logging internal logs to D:\rushan\II\lab3\II_Group1_Lab3\wandb\run-20211209_092426-8gooktbx\logs\debug-internal.log
2021-12-09 09:24:26,211 INFO    MainThread:12500 [wandb_init.py:init():404] calling init triggers
2021-12-09 09:24:26,211 INFO    MainThread:12500 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2021-12-09 09:24:26,213 INFO    MainThread:12500 [wandb_init.py:init():426] re-initializing run, found existing run on stack: qlilun14
2021-12-09 09:24:26,213 INFO    MainThread:12500 [wandb_run.py:finish():1463] finishing run marvink/lab3/qlilun14
2021-12-09 09:24:26,333 INFO    MainThread:12500 [jupyter.py:save_history():429] not saving jupyter history
2021-12-09 09:24:26,333 INFO    MainThread:12500 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-09 09:24:26,333 INFO    MainThread:12500 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2021-12-09 09:24:26,333 INFO    MainThread:12500 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 0
2021-12-09 09:24:26,333 INFO    MainThread:12500 [wandb_run.py:_restore():1758] restore
2021-12-09 09:24:27,010 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 791
  total_bytes: 791
}

2021-12-09 09:24:27,229 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 791
  total_bytes: 791
}

2021-12-09 09:24:27,797 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 791
  total_bytes: 11930
}

2021-12-09 09:24:27,900 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 791
  total_bytes: 11930
}

2021-12-09 09:24:28,001 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1010
  total_bytes: 11930
}

2021-12-09 09:24:28,103 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11930
  total_bytes: 11930
}

2021-12-09 09:24:28,204 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11930
  total_bytes: 11930
}

2021-12-09 09:24:28,306 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11930
  total_bytes: 11930
}

2021-12-09 09:24:28,409 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11930
  total_bytes: 11930
}

2021-12-09 09:24:28,509 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11930
  total_bytes: 11930
}

2021-12-09 09:24:28,933 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11930
  total_bytes: 11930
}

2021-12-09 09:24:29,343 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11930
  total_bytes: 11930
}
local_info {
}

2021-12-09 09:24:30,465 INFO    MainThread:12500 [wandb_run.py:_append_files():2184] logging synced files
2021-12-09 09:24:30,468 INFO    MainThread:12500 [wandb_init.py:init():449] starting backend
2021-12-09 09:24:30,469 INFO    MainThread:12500 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2021-12-09 09:24:30,472 INFO    MainThread:12500 [backend.py:ensure_launched():199] starting backend process...
2021-12-09 09:24:30,531 INFO    MainThread:12500 [backend.py:ensure_launched():205] started backend process with pid: 10128
2021-12-09 09:24:30,532 INFO    MainThread:12500 [wandb_init.py:init():458] backend started and connected
2021-12-09 09:24:30,533 INFO    MainThread:12500 [wandb_run.py:_label_probe_notebook():917] probe notebook
2021-12-09 09:24:30,533 INFO    MainThread:12500 [wandb_run.py:_label_probe_notebook():927] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-12-09 09:24:30,533 INFO    MainThread:12500 [wandb_init.py:init():519] updated telemetry
2021-12-09 09:24:30,736 INFO    MainThread:12500 [wandb_init.py:init():549] communicating current version
2021-12-09 09:24:32,083 INFO    MainThread:12500 [wandb_init.py:init():554] got version response 
2021-12-09 09:24:32,084 INFO    MainThread:12500 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-12-09 09:24:32,274 INFO    MainThread:12500 [wandb_init.py:init():592] starting run threads in backend
2021-12-09 09:24:35,447 INFO    MainThread:12500 [wandb_run.py:_console_start():1816] atexit reg
2021-12-09 09:24:35,448 INFO    MainThread:12500 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.WRAP
2021-12-09 09:24:35,448 INFO    MainThread:12500 [wandb_run.py:_redirect():1727] Wrapping output streams.
2021-12-09 09:24:35,450 INFO    MainThread:12500 [wandb_run.py:_redirect():1751] Redirects installed.
2021-12-09 09:24:35,450 INFO    MainThread:12500 [wandb_init.py:init():619] run started, returning control to user process
2021-12-09 09:24:35,450 INFO    MainThread:12500 [wandb_config.py:__setitem__():144] config set batch_size = 512 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000015C3ABCAF88>>
2021-12-09 09:24:35,450 INFO    MainThread:12500 [wandb_run.py:_config_callback():962] config_cb batch_size 512 None
2021-12-09 09:24:35,450 INFO    MainThread:12500 [wandb_config.py:__setitem__():144] config set epochs = 40 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000015C3ABCAF88>>
2021-12-09 09:24:35,450 INFO    MainThread:12500 [wandb_run.py:_config_callback():962] config_cb epochs 40 None
2021-12-09 09:24:35,451 INFO    MainThread:12500 [wandb_config.py:__setitem__():144] config set lr = 0.0001 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000015C3ABCAF88>>
2021-12-09 09:24:35,451 INFO    MainThread:12500 [wandb_run.py:_config_callback():962] config_cb lr 0.0001 None
2021-12-09 09:24:49,567 INFO    MainThread:12500 [wandb_setup.py:_flush():71] setting env: {}
2021-12-09 09:24:49,567 INFO    MainThread:12500 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-09 09:24:49,567 INFO    MainThread:12500 [wandb_init.py:_log_setup():371] Logging user logs to D:\rushan\II\lab3\II_Group1_Lab3\wandb\run-20211209_092449-22znctwl\logs\debug.log
2021-12-09 09:24:49,567 INFO    MainThread:12500 [wandb_init.py:_log_setup():372] Logging internal logs to D:\rushan\II\lab3\II_Group1_Lab3\wandb\run-20211209_092449-22znctwl\logs\debug-internal.log
2021-12-09 09:24:49,567 INFO    MainThread:12500 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000015BB4113708>
2021-12-09 09:24:49,568 INFO    MainThread:12500 [wandb_init.py:init():404] calling init triggers
2021-12-09 09:24:49,568 INFO    MainThread:12500 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2021-12-09 09:24:49,568 INFO    MainThread:12500 [wandb_init.py:init():426] re-initializing run, found existing run on stack: 8gooktbx
2021-12-09 09:24:49,568 INFO    MainThread:12500 [wandb_run.py:finish():1463] finishing run marvink/lab3/8gooktbx
2021-12-09 09:24:49,568 INFO    MainThread:12500 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 0
2021-12-09 09:24:49,569 INFO    MainThread:12500 [wandb_run.py:_restore():1758] restore
2021-12-09 09:24:49,973 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 791
  total_bytes: 791
}

2021-12-09 09:24:50,226 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 791
  total_bytes: 791
}

2021-12-09 09:24:50,327 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 791
  total_bytes: 11930
}

2021-12-09 09:24:50,428 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 791
  total_bytes: 11930
}

2021-12-09 09:24:50,530 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11930
  total_bytes: 11930
}

2021-12-09 09:24:50,631 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11930
  total_bytes: 11930
}

2021-12-09 09:24:50,734 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11930
  total_bytes: 11930
}

2021-12-09 09:24:50,834 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11930
  total_bytes: 11930
}

2021-12-09 09:24:50,936 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11930
  total_bytes: 11930
}

2021-12-09 09:24:51,318 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11930
  total_bytes: 11930
}

2021-12-09 09:24:51,721 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11930
  total_bytes: 11930
}
local_info {
}

2021-12-09 09:24:52,833 INFO    MainThread:12500 [wandb_run.py:_append_files():2184] logging synced files
