2021-12-09 09:28:27,915 INFO    MainThread:12500 [wandb_setup.py:_flush():71] setting env: {}
2021-12-09 09:28:27,915 INFO    MainThread:12500 [wandb_setup.py:_flush():71] setting login settings: {}
2021-12-09 09:28:27,915 INFO    MainThread:12500 [wandb_init.py:_log_setup():371] Logging user logs to D:\rushan\II\lab3\II_Group1_Lab3\wandb\run-20211209_092827-175u6pu5\logs\debug.log
2021-12-09 09:28:27,916 INFO    MainThread:12500 [wandb_init.py:_log_setup():372] Logging internal logs to D:\rushan\II\lab3\II_Group1_Lab3\wandb\run-20211209_092827-175u6pu5\logs\debug-internal.log
2021-12-09 09:28:27,916 INFO    MainThread:12500 [wandb_init.py:init():404] calling init triggers
2021-12-09 09:28:27,916 INFO    MainThread:12500 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2021-12-09 09:28:27,916 INFO    MainThread:12500 [wandb_init.py:init():426] re-initializing run, found existing run on stack: 22znctwl
2021-12-09 09:28:27,916 INFO    MainThread:12500 [wandb_run.py:finish():1463] finishing run marvink/lab3/22znctwl
2021-12-09 09:28:27,916 INFO    MainThread:12500 [jupyter.py:save_history():429] not saving jupyter history
2021-12-09 09:28:27,917 INFO    MainThread:12500 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-12-09 09:28:27,917 INFO    MainThread:12500 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2021-12-09 09:28:27,917 INFO    MainThread:12500 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 0
2021-12-09 09:28:27,917 INFO    MainThread:12500 [wandb_run.py:_restore():1758] restore
2021-12-09 09:28:28,819 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 791
  total_bytes: 791
}

2021-12-09 09:28:29,060 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 791
  total_bytes: 791
}

2021-12-09 09:28:29,789 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 791
  total_bytes: 11998
}

2021-12-09 09:28:29,889 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 791
  total_bytes: 12119
}

2021-12-09 09:28:29,992 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11683
  total_bytes: 12119
}

2021-12-09 09:28:30,094 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12119
  total_bytes: 12119
}

2021-12-09 09:28:30,195 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12119
  total_bytes: 12119
}

2021-12-09 09:28:30,298 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12119
  total_bytes: 12119
}

2021-12-09 09:28:30,400 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12119
  total_bytes: 12119
}

2021-12-09 09:28:30,501 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12119
  total_bytes: 12119
}

2021-12-09 09:28:30,828 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12119
  total_bytes: 12119
}

2021-12-09 09:28:31,240 INFO    MainThread:12500 [wandb_run.py:_wait_for_finish():1916] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 12119
  total_bytes: 12119
}
local_info {
}

2021-12-09 09:28:32,358 INFO    MainThread:12500 [wandb_run.py:_append_history():2134] rendering history
2021-12-09 09:28:32,358 INFO    MainThread:12500 [wandb_run.py:_append_summary():2089] rendering summary
2021-12-09 09:28:32,358 INFO    MainThread:12500 [wandb_run.py:_append_files():2184] logging synced files
2021-12-09 09:28:32,361 INFO    MainThread:12500 [wandb_init.py:init():449] starting backend
2021-12-09 09:28:32,361 INFO    MainThread:12500 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2021-12-09 09:28:32,364 INFO    MainThread:12500 [backend.py:ensure_launched():199] starting backend process...
2021-12-09 09:28:32,425 INFO    MainThread:12500 [backend.py:ensure_launched():205] started backend process with pid: 2392
2021-12-09 09:28:32,426 INFO    MainThread:12500 [wandb_init.py:init():458] backend started and connected
2021-12-09 09:28:32,426 INFO    MainThread:12500 [wandb_run.py:_label_probe_notebook():917] probe notebook
2021-12-09 09:28:32,426 INFO    MainThread:12500 [wandb_run.py:_label_probe_notebook():927] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-12-09 09:28:32,426 INFO    MainThread:12500 [wandb_init.py:init():519] updated telemetry
2021-12-09 09:28:32,676 INFO    MainThread:12500 [wandb_init.py:init():549] communicating current version
2021-12-09 09:28:33,919 INFO    MainThread:12500 [wandb_init.py:init():554] got version response 
2021-12-09 09:28:33,919 INFO    MainThread:12500 [wandb_init.py:init():564] communicating run to backend with 30 second timeout
2021-12-09 09:28:34,102 INFO    MainThread:12500 [wandb_init.py:init():592] starting run threads in backend
2021-12-09 09:28:37,254 INFO    MainThread:12500 [wandb_run.py:_console_start():1816] atexit reg
2021-12-09 09:28:37,255 INFO    MainThread:12500 [wandb_run.py:_redirect():1690] redirect: SettingsConsole.WRAP
2021-12-09 09:28:37,255 INFO    MainThread:12500 [wandb_run.py:_redirect():1727] Wrapping output streams.
2021-12-09 09:28:37,257 INFO    MainThread:12500 [wandb_run.py:_redirect():1751] Redirects installed.
2021-12-09 09:28:37,257 INFO    MainThread:12500 [wandb_init.py:init():619] run started, returning control to user process
2021-12-09 09:28:37,257 INFO    MainThread:12500 [wandb_config.py:__setitem__():144] config set batch_size = 256 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000015BB40F9748>>
2021-12-09 09:28:37,257 INFO    MainThread:12500 [wandb_run.py:_config_callback():962] config_cb batch_size 256 None
2021-12-09 09:28:37,257 INFO    MainThread:12500 [wandb_config.py:__setitem__():144] config set epochs = 40 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000015BB40F9748>>
2021-12-09 09:28:37,257 INFO    MainThread:12500 [wandb_run.py:_config_callback():962] config_cb epochs 40 None
2021-12-09 09:28:37,257 INFO    MainThread:12500 [wandb_config.py:__setitem__():144] config set lr = 0.001 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000015BB40F9748>>
2021-12-09 09:28:37,258 INFO    MainThread:12500 [wandb_run.py:_config_callback():962] config_cb lr 0.001 None
2021-12-09 17:07:21,628 INFO    MainThread:12500 [wandb_run.py:_atexit_cleanup():1786] got exitcode: 0
2021-12-09 17:07:21,630 INFO    MainThread:12500 [wandb_run.py:_restore():1758] restore
